version: '2'

services:

  resolver:
    build:
      context: ./RESOLVER
      dockerfile: Dockerfile
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      local:
          ipv4_address: 172.16.0.2
    volumes:
      - ./RESOLVER/named.conf:/etc/bind/named.conf
    container_name: RESOLVER

  soa-in:
    build:
      context: ./SOA-in
      dockerfile: Dockerfile
    networks:
      local:
          ipv4_address: 172.16.0.3
    volumes:
      - ./SOA-in/named.conf:/etc/bind/named.conf
      - ./SOA-in/intranet.m1-5.ephec-ti.be:/etc/bind/intranet.m1-5.ephec-ti.be
      - ./SOA-in/reverse:/etc/bind/reverse
    container_name: SOA-in

networks:
  local:
      ipam:
          driver: default
          config:
              - subnet: 172.16.0.0/24
                gateway: 172.16.0.1
